### ISSUE TITLE
Builds ok ..fails on device

### ISSUE THREAD

**Issue by dvescovi1** [ms-iot/RPi-UEFI#1]
Rebuild according to directions. Build completed OK and created kernel.img file of the exact same size as kernel.img generated with IoT dashboard set up. Replaced kernel.img on card with my generated kernel.img and it no longer boot. On screen I get "Graphics Console Started" then nothing.

**Comment by dvescovi1** [comment]
I think this error may be because I was building the "DEBUG" version ...which is the default after setting up the tools. The "RELEASE" version appears to boot and works ok. Please fix for debug builds.

**Comment by N1N** [comment]
@dvescovi1 Apart from kernel.img, did you replace any other file in the SD card (start.elf,bootcode.bin.. etc.,)?? 
My built kernel.img file size is 896 kb, and the one which is there in the card is 864kb.
Can you pls share the steps you have followed to generate kernel.img from UEFI source??

**Comment by dvescovi1** [comment]
I did not replace any other file. The size looks the same as what I got. Be sure to do a RELEASE build.
