### ISSUE TITLE
Use VS for ARM based builds

### ISSUE THREAD

**Issue by dvescovi1** [ms-iot/RPi-UEFI#3]
This project should support build using Visual Studio with its ARM compiler for ARM based targets.

**Comment by serusako** [comment]
Sorry which project do you refer to ? Visual Studio 2015 does build applications and drivers for ARM platform just fine.

**Comment by dvescovi1** [comment]
I'm referring to THIS project. someone needs to integrate the VS tool chain and use its ARM compiler.
Right now the only way you can build this project is use the windows GNU compiler.

**Comment by serusako** [comment]
Ok  you are asking about RPi UEFI project. Sure go ahead and make necessary changes to use VS2015 instead of GCC tool chain. We encourage community contribution!

**Comment by saraclay** [comment]
If this issue is still relevant, please file this at: https://github.com/MicrosoftDocs/windows-iotcore-docs
