### ISSUE TITLE
UEFI build error : "arm-none-eabi-gcc" is not recognized as an internal or external command

### ISSUE THREAD

**Issue by N1N** [ms-iot/RPi-UEFI#4]
Hi,

I am trying to build the UEFI source code by executing 'BuildPi2Board.bat' for Rpi2 Board without modifying the source code.

But I am getting the following error,

UEFI build error : "arm-none-eabi-gcc" is not recognized as an internal or external command.

I have already installed GCC in my system using Cygwin.

Please suggest.

------------------------------- My log -------------------------------

C:\RPi-UEFI-ms-iot\RPi-UEFI-ms-iot>BuildPi2Board.bat
Build window not configured, configuring it ...
          PATH      = C:\RPi-UEFI-ms-iot\RPi-UEFI-ms-iot\BaseTools\Bin;C:\RPi-UEFI-ms-iot\RPi-UEFI-ms-iot\BaseTools\Bin\Win32;C:\RPi-UEFI-ms-iot\EDK2\BaseTools\Bin;C:\RPi-UEFI-ms-iot\EDK2\BaseTools\Bin\Win32;C:\RPi-UEFI-ms-iot\ToolChains\Arm\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\TortoiseSVN\bin;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\WINDOWS\SysWOW64\WindowsPowerShell\v1.0\Modules\TShell\TShell\;C:\Users\iw-hd-dtp-93\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;

     WORKSPACE      = C:\RPi-UEFI-ms-iot\RPi-UEFI-ms-iot
EDK_TOOLS_PATH      = C:\RPi-UEFI-ms-iot\RPi-UEFI-ms-iot\BaseTools

Rebuilding of tools is not required.  Binaries of the latest,
tested versions of the tools have been tested and included in the
EDK II repository.

If you really want to build the tools, use the ForceRebuild option.

!!! WARNING !!! No CYGWIN_HOME set, gcc build may not be used !!!

Config DEBUG Build Window ## Succeeded ##

EDKROOT_DIR = C:\RPi-UEFI-ms-iot\RPi-UEFI-ms-iot
PI_FLAVOR = Pi2
PI2_PKG_PATH = C:\RPi-UEFI-ms-iot\RPi-UEFI-ms-iot\Pi2BoardPkg\Pi2BoardPkg.dsc
Build environment: Windows-post2008Server-6.2.9200
Build start time: 16:13:52, Nov.22 2016

WORKSPACE        = c:\rpi-uefi-ms-iot\rpi-uefi-ms-iot
ECP_SOURCE       = c:\rpi-uefi-ms-iot\rpi-uefi-ms-iot\edkcompatibilitypkg
EDK_SOURCE       = c:\rpi-uefi-ms-iot\rpi-uefi-ms-iot\edkcompatibilitypkg
EFI_SOURCE       = c:\rpi-uefi-ms-iot\rpi-uefi-ms-iot\edkcompatibilitypkg
EDK_TOOLS_PATH   = c:\rpi-uefi-ms-iot\rpi-uefi-ms-iot\basetools

Architecture(s)  = ARM
Build target     = DEBUG
Toolchain        = ARMGCC

Active Platform          = c:\rpi-uefi-ms-iot\rpi-uefi-ms-iot\Pi2BoardPkg\Pi2BoardPkg.dsc
Flash Image Definition   = c:\rpi-uefi-ms-iot\rpi-uefi-ms-iot\Pi2BoardPkg\Pi2BoardPkg.fdf

Processing meta-data ...... done!
Building ... c:\rpi-uefi-ms-iot\rpi-uefi-ms-iot\MdePkg\Library\BasePeCoffExtraActionLibNull\BasePeCoffExtraActionLibNull.inf [ARM]
Building ... c:\rpi-uefi-ms-iot\rpi-uefi-ms-iot\ArmPlatformPkg\Library\ArmPlatformGlobalVariableLib\Sec\SecArmPlatformGlobalVariableLib.inf [ARM]
Building ... c:\rpi-uefi-ms-iot\rpi-uefi-ms-iot\ArmPlatformPkg\Library\PrePiHobListPointerLib\PrePiHobListPointerLib.inf [ARM]
Building ... c:\rpi-uefi-ms-iot\rpi-uefi-ms-iot\EmbeddedPkg\Library\PrePiHobLib\PrePiHobLib.inf [ARM]
"arm-none-eabi-gcc"  -march=armv7-a -g -Os -fshort-wchar -fno-strict-aliasing -Wall -Werror -Wno-array-bounds -c -include AutoGen.h -mword-relocations -mlittle-endian -mabi=aapcs -mapcs -fno-short-enums -save-temps -fsigned-char -ffunction-sections -fdata-sections -fomit-frame-pointer -Wno-address -mthumb -mfloat-abi=hard -O0 -o c:\rpi-uefi-ms-iot\rpi-uefi-ms-iot\Build\Pi2Board\DEBUG_ARMGCC\ARM\ArmPlatformPkg\Library\ArmPlatformGlobalVariableLib\Sec\SecArmPlatformGlobalVariableLib\OUTPUT\.\SecArmPlatformGlobalVariableLib.obj -Ic:\rpi-uefi-ms-iot\rpi-uefi-ms-iot\ArmPlatformPkg\Library\ArmPlatformGlobalVariableLib\Sec -Ic:\rpi-uefi-ms-iot\rpi-uefi-ms-iot\Build\Pi2Board\DEBUG_ARMGCC\ARM\ArmPlatformPkg\Library\ArmPlatformGlobalVariableLib\Sec\SecArmPlatformGlobalVariableLib\DEBUG -Ic:\rpi-uefi-ms-iot\rpi-uefi-ms-iot\MdePkg -Ic:\rpi-uefi-ms-iot\rpi-uefi-ms-iot\MdePkg\Include -Ic:\rpi-uefi-ms-iot\rpi-uefi-ms-iot\MdePkg\Include\Arm -Ic:\rpi-uefi-ms-iot\rpi-uefi-ms-iot\ArmPlatformPkg -Ic:\rpi-uefi-ms-iot\rpi-uefi-ms-iot\ArmPlatformPkg\Include c:\rpi-uefi-ms-iot\rpi-uefi-ms-iot\ArmPlatformPkg\Library\ArmPlatformGlobalVariableLib\Sec\SecArmPlatformGlobalVariableLib.c
"arm-none-eabi-gcc"  -march=armv7-a -g -Os -fshort-wchar -fno-strict-aliasing -Wall -Werror -Wno-array-bounds -c -include AutoGen.h -mword-relocations -mlittle-endian -mabi=aapcs -mapcs -fno-short-enums -save-temps -fsigned-char -ffunction-sections -fdata-sections -fomit-frame-pointer -Wno-address -mthumb -mfloat-abi=hard -O0 -o c:\rpi-uefi-ms-iot\rpi-uefi-ms-iot\Build\Pi2Board\DEBUG_ARMGCC\ARM\MdePkg\Library\BasePeCoffExtraActionLibNull\BasePeCoffExtraActionLibNull\OUTPUT\.\PeCoffExtraActionLib.obj -Ic:\rpi-uefi-ms-iot\rpi-uefi-ms-iot\MdePkg\Library\BasePeCoffExtraActionLibNull -Ic:\rpi-uefi-ms-iot\rpi-uefi-ms-iot\Build\Pi2Board\DEBUG_ARMGCC\ARM\MdePkg\Library\BasePeCoffExtraActionLibNull\BasePeCoffExtraActionLibNull\DEBUG -Ic:\rpi-uefi-ms-iot\rpi-uefi-ms-iot\MdePkg -Ic:\rpi-uefi-ms-iot\rpi-uefi-ms-iot\MdePkg\Include -Ic:\rpi-uefi-ms-iot\rpi-uefi-ms-iot\MdePkg\Include\Arm c:\rpi-uefi-ms-iot\rpi-uefi-ms-iot\MdePkg\Library\BasePeCoffExtraActionLibNull\PeCoffExtraActionLib.c
"arm-none-eabi-gcc"  -march=armv7-a -g -Os -fshort-wchar -fno-strict-aliasing -Wall -Werror -Wno-array-bounds -c -include AutoGen.h -mword-relocations -mlittle-endian -mabi=aapcs -mapcs -fno-short-enums -save-temps -fsigned-char -ffunction-sections -fdata-sections -fomit-frame-pointer -Wno-address -mthumb -mfloat-abi=hard -O0 -o c:\rpi-uefi-ms-iot\rpi-uefi-ms-iot\Build\Pi2Board\DEBUG_ARMGCC\ARM\ArmPlatformPkg\Library\PrePiHobListPointerLib\PrePiHobListPointerLib\OUTPUT\.\PrePiHobListPointer.obj -Ic:\rpi-uefi-ms-iot\rpi-uefi-ms-iot\ArmPlatformPkg\Library\PrePiHobListPointerLib -Ic:\rpi-uefi-ms-iot\rpi-uefi-ms-iot\Build\Pi2Board\DEBUG_ARMGCC\ARM\ArmPlatformPkg\Library\PrePiHobListPointerLib\PrePiHobListPointerLib\DEBUG -Ic:\rpi-uefi-ms-iot\rpi-uefi-ms-iot\MdePkg -Ic:\rpi-uefi-ms-iot\rpi-uefi-ms-iot\MdePkg\Include -Ic:\rpi-uefi-ms-iot\rpi-uefi-ms-iot\MdePkg\Include\Arm -Ic:\rpi-uefi-ms-iot\rpi-uefi-ms-iot\ArmPlatformPkg -Ic:\rpi-uefi-ms-iot\rpi-uefi-ms-iot\ArmPlatformPkg\Include -Ic:\rpi-uefi-ms-iot\rpi-uefi-ms-iot\EmbeddedPkg -Ic:\rpi-uefi-ms-iot\rpi-uefi-ms-iot\EmbeddedPkg\Include c:\rpi-uefi-ms-iot\rpi-uefi-ms-iot\ArmPlatformPkg\Library\PrePiHobListPointerLib\PrePiHobListPointer.c
'"arm-none-eabi-gcc"' is not recognized as an internal or external command,
'"arm-none-eabi-gcc"' is not recognized as an internal or external command,
'"arm-none-eabi-gcc"' is not recognized as an internal or external command,
operable program or batch file.
operable program or batch file.
operable program or batch file.
make: *** [c:\rpi-uefi-ms-iot\rpi-uefi-ms-iot\Build\Pi2Board\DEBUG_ARMGCC\ARM\ArmPlatformPkg\Library\ArmPlatformGlobalVariableLib\Sec\SecArmPlatformGlobalVariableLib\OUTPUT\SecArmPlatformGlobalVariableLib.obj] Error 1
"marm-none-eabi-gcc"  -march=armv7-a -g -Os -fshort-wchar -fno-strict-aliasing -Wall -Werror -Wno-array-bounds -c -include AutoGen.h -mword-relocations -mlittle-endian -mabi=aapcs -mapcs -fno-short-enums -save-temps -fsigned-char -ffunction-sections -fdata-sections -fomit-frame-pointer -Wno-address -mthumb -mfloat-abi=hard -O0 -o c:\rpi-uefi-ms-iot\rpi-uefi-ms-iot\Build\Pi2Board\DEBUG_ARMGCC\ARM\EmbeddedPkg\Library\PrePiHobLib\PrePiHobLib\OUTPUT\.\Hob.obj -Ic:\rpi-uefi-ms-iot\rpi-uefi-ms-iot\EmbeddedPkg\Library\PrePiHobLib -Ic:\rpi-uefi-ms-iot\rpi-uefi-ms-iot\Build\Pi2Board\DEBUG_ARMGCC\ARM\EmbeddedPkg\Library\PrePiHobLib\PrePiHobLib\DEBUG -Ic:\rpi-uefi-ms-iot\rpi-uefi-ms-iot\MdePkg -Ic:\rpi-uefi-ms-iot\rpi-uefi-ms-iot\MdePkg\Include -Ic:\rpi-uefi-ms-iot\rpi-uefi-ms-iot\MdePkg\Include\Arm -Ic:\rpi-uefi-ms-iot\rpi-uefi-ms-iot\MdeModulePkg -Ic:\rpi-uefi-ms-iot\rpi-uefi-ms-iot\MdeModulePkg\Include -Ic:\rpi-uefi-ms-iot\rpi-uefi-ms-iot\EmbeddedPkg -Ic:\rpi-uefi-ms-iot\rpi-uefi-ms-iot\EmbeddedPkg\Include c:\rpi-uefi-ms-iot\rpi-uefi-ms-iot\EmbeddedPkg\Library\PrePiHobLib\Hob.c
ake: *** [c:\rpi-uefi-ms-iot\rpi-uefi-ms-iot\Build\Pi2Board\DEBUG_ARMGCC\ARM\ArmPlatformPkg\Library\PrePiHobListPointerLib\PrePiHobListPointerLib\OUTPUT\PrePiHobListPointer.obj] Error 1
make: *** [c:\rpi-uefi-ms-iot\rpi-uefi-ms-iot\Build\Pi2Board\DEBUG_ARMGCC\ARM\MdePkg\Library\BasePeCoffExtraActionLibNull\BasePeCoffExtraActionLibNull\OUTPUT\PeCoffExtraActionLib.obj] Error 1

build...
 : error 7000: Failed to execute command
        make --no-print-directory tbuild [c:\rpi-uefi-ms-iot\rpi-uefi-ms-iot\Build\Pi2Board\DEBUG_ARMGCC\ARM\ArmPlatformPkg\Library\ArmPlatformGlobalVariableLib\Sec\SecArmPlatformGlobalVariableLib]

build...
 : error 7000: Failed to execute command
        make --no-print-directory tbuild [c:\rpi-uefi-ms-iot\rpi-uefi-ms-iot\Build\Pi2Board\DEBUG_ARMGCC\ARM\ArmPlatformPkg\Library\PrePiHobListPointerLib\PrePiHobListPointerLib]

build...
 : error 7000: Failed to execute command
        make --no-print-directory tbuild [c:\rpi-uefi-ms-iot\rpi-uefi-ms-iot\Build\Pi2Board\DEBUG_ARMGCC\ARM\MdePkg\Library\BasePeCoffExtraActionLibNull\BasePeCoffExtraActionLibNull]

build...
 : error 7000: Failed to execute command
        make --no-print-directory tbuild [c:\rpi-uefi-ms-iot\rpi-uefi-ms-iot\Build\Pi2Board\DEBUG_ARMGCC\ARM\EmbeddedPkg\Library\PrePiHobLib\PrePiHobLib]

build...
 : error 7000: Failed to execute command
        make --no-print-directory tbuild [c:\rpi-uefi-ms-iot\rpi-uefi-ms-iot\Build\Pi2Board\DEBUG_ARMGCC\ARM\MdePkg\Library\BasePerformanceLibNull\BasePerformanceLibNull]

build...
 : error F002: Failed to build module
        c:\rpi-uefi-ms-iot\rpi-uefi-ms-iot\ArmPlatformPkg\Library\ArmPlatformGlobalVariableLib\Sec\SecArmPlatformGlobalVariableLib.inf [ARM, ARMGCC, DEBUG]

- Failed -
Build end time: 16:14:00, Nov.22 2016
Build total time: 00:00:08

Pi2 Boot Image Build ## Failed ##

C:\RPi-UEFI-ms-iot\RPi-UEFI-ms-iot>

------------------------------- My log -------------------------------

Regards,
N1N

**Comment by dvescovi1** [comment]
you don't need Cygwin. you need the standard Windows desktop version of the GCC ARM compiler.

**Comment by N1N** [comment]
Thanks for the suggestion @dvescovi1. Worked by installing Windows desktop version of GCC ARM Compiler.
