### ISSUE TITLE
Windows 10 IoT  - UEFI kernel.img

### ISSUE THREAD

**Issue by N1N** [ms-iot/RPi-UEFI#5]
Hi,

I am using RPi2 board and running Windows 10 IoT on it.

I have gone through the following article,
https://msdn.microsoft.com/en-us/windows/hardware/drivers/bringup/boot-and-uefi

This article says, UEFI environment loads the Main OS.

But when i go through the UEFI, BSP, and Firmware source code directory structure, i did not understand which binary file is considered as OS Main image.

Is it kernel.img which we get Once we build the UEFI source using 'BuildPi2Board.bat'? or some other binary file?

I understand bootcode.bin,start.elf are pre-built binaries which are part of Firmware.
Kernel.img will be generated once we build the UEFI source code.
Same way Which is the OS image?

Please help me out!!

Regards,
NaN

**Comment by serusako** [comment]
Hi,
unlike in Linux, Windows does not have single OS image. OS is stored in a separate partition named MAINOS on the same SD card as set of many files, similar to what you see on PC.

**Comment by dvescovi1** [comment]
You did not answer his question. The answer is yes you do get Kernel.img after you build this project.
When you finish building you have a PI2BOARD_EFI.fd file which is renamed by the build script to kernel.img. This is the boot file that is copied to the SD card that starts the OS load process.

**Comment by serusako** [comment]
Sorry I misread your question. You were asking
Q: Which is the OS image?
and I provided answer to that question. 
A: Neither PI2BOARD_EFI.fd nor kernel.img is OS image.

**Comment by IoTGirl** [comment]
Hi N1N,
I am closing this issue based on the answers given.  For further information on creating the OS image, please review the documentation at [https://msdn.microsoft.com/en-us/library/windows/hardware/dn916104](https://msdn.microsoft.com/en-us/library/windows/hardware/dn916104%28v=vs.85%29.aspx)

For OS image creation, you can give feedback directly at that page when it asks you "Is this page helpful?"

Sincerely,
IoTGirl
