### ISSUE TITLE
Colour screen in Windows 10 IoT

### ISSUE THREAD

**Issue by N1N** [ms-iot/RPi-UEFI#6]
Hi,

I am using RPi2 board. I have generated FFU image using ICD and flashed it to SD card. It is booting successfuly.

But when i build the UEFI source code(By running BuildPi2Board.bat), and if i copy the generated kernel.img in to SD card,(by replacing the existing kernel.img in the card), It is stuck at showing a color display.

Please suggest!

Regards

**Comment by dvescovi1** [comment]
Make sure you are building the "RELEASE" version (as set in the target.txt in the Conf folder) the default "DEBUG" version appears to have never been tested (among other things).

**Comment by N1N** [comment]
Hi dvescovi1,

Thanks for the Reply!

I changed the value of TARGET as 'TARGET  = RELEASE' in target.txt file and i am getting the kernel.img binary under Build\Pi2Board\RELEASE_ARMGCC\ folder.

But the issues still exists.

Anything else i am missing?

Regards.

**Comment by serusako** [comment]
Hi, If you see gradient color screen on your monitor while booting RPi, then the bootloader worked, but UEFI did not start. There may be a variety of reasons why.
Are you by chance using RPi2 v1.2 board ?

**Comment by IoTGirl** [comment]
No answer - Closing as stale
