### ISSUE TITLE
USB Support

### ISSUE THREAD

**Issue by andydahlen** [ms-iot/RPi-UEFI#8]
The current RPi-UEFI lacks USB support. Would it be possible to incorporate USB drivers? This would allow booting from USB devices which opens up a wide range of options for recovery and updating devices in the field. Not mention the add benefit of not being reliant on SD Cards which have a high failure rate on IOT Core without the use of a Unified Write Filter.

**Comment by saraclay** [comment]
If this issue is still relevant, please file this at: https://github.com/MicrosoftDocs/windows-iotcore-docs
